# -*- coding: utf-8 -*-

# DashboardInterface implementation generated from reading ui file '/Users/taohong/Programs/course-projects/face-detect/gui/pyqt_ui/dashboard_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QHBoxLayout, QVBoxLayout
from qfluentwidgets import StrongBodyLabel, HorizontalFlipView, ListWidget, CardWidget, ElevatedCardWidget


class Ui_dashboardInterface(object):
    def setupUi(self, DashboardInterface):
        DashboardInterface.setObjectName("DashboardInterface")
        DashboardInterface.resize(851, 619)
        self.listCard1 = ElevatedCardWidget(DashboardInterface)
        self.listCard1.setObjectName("listCard1")
        self.listCard1.setGeometry(QtCore.QRect(440, 330, 370, 270))
        self.unsigned_list = ListWidget(DashboardInterface)
        self.unsigned_list.setGeometry(QtCore.QRect(440, 330, 360, 261))
        self.unsigned_list.setObjectName("unsigned_list")
        layout = QVBoxLayout(self.listCard1)
        layout.setContentsMargins(5, 5, 5, 5)
        layout.addWidget(self.unsigned_list)

        self.listCard2 = ElevatedCardWidget(DashboardInterface)
        self.listCard2.setObjectName("listCard2")
        self.listCard2.setGeometry(QtCore.QRect(40, 330, 370, 270))
        self.signed_list = ListWidget(DashboardInterface)
        self.signed_list.setGeometry(QtCore.QRect(40, 330, 360, 261))
        self.signed_list.setObjectName("signed_list")
        layout2 = QVBoxLayout(self.listCard2)
        layout2.setContentsMargins(5, 5, 5, 5)
        layout2.addWidget(self.signed_list)

        self.label = StrongBodyLabel(DashboardInterface)
        self.label.setGeometry(QtCore.QRect(40, 300, 91, 21))
        self.label.setObjectName("label")
        self.label_2 = StrongBodyLabel(DashboardInterface)
        self.label_2.setGeometry(QtCore.QRect(440, 300, 91, 21))
        self.label_2.setObjectName("label_2")
        self.flip = HorizontalFlipView(DashboardInterface)
        self.flip.setGeometry(QtCore.QRect(40, 40, 770, 250))
        self.flip.setObjectName("flip")
        self.label_3 = StrongBodyLabel(DashboardInterface)
        self.label_3.setGeometry(QtCore.QRect(40, 10, 91, 21))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(DashboardInterface)
        QtCore.QMetaObject.connectSlotsByName(DashboardInterface)

    def retranslateUi(self, DashboardInterface):
        _translate = QtCore.QCoreApplication.translate
        DashboardInterface.setWindowTitle(_translate("DashboardInterface", "DashboardInterface"))
        self.label.setText(_translate("DashboardInterface", "已签到名单"))
        self.label_2.setText(_translate("DashboardInterface", "未签到名单"))
        self.label_3.setText(_translate("DashboardInterface", "课堂公告"))
