# -*- coding: utf-8 -*-

# Form implementation generated from reading gui file '/Users/taohong/Programs/course-projects/face-detect/gui/pyqt_ui/register_face_interface.gui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QDate
from PyQt5.QtWidgets import QHBoxLayout, QButtonGroup
from qfluentwidgets import StrongBodyLabel, LineEdit, PushButton, ImageLabel, ElevatedCardWidget, RadioButton, ZhDatePicker


class Ui_registerInterface(object):
    def setupUi(self, RegisterInterface):
        RegisterInterface.setObjectName("registerFaceInterface")
        RegisterInterface.resize(850, 620)
        RegisterInterface.setMinimumSize(QtCore.QSize(760, 560))
        RegisterInterface.setMaximumSize(QtCore.QSize(760, 560))
        self.image_card = ElevatedCardWidget(RegisterInterface)
        self.image_card.setObjectName("ImageCard")
        self.image_card.setGeometry(50, 100, 300, 300)
        self.label_avatar = ImageLabel(RegisterInterface)
        self.label_avatar.setImage("assets/default_avatar.png")
        self.label_avatar.setObjectName("label_avatar")
        self.label_avatar.setGeometry(50, 100, 300, 300)
        layout = QHBoxLayout(self.image_card)
        layout.addWidget(self.label_avatar)
        self.label_name = StrongBodyLabel(RegisterInterface)
        self.label_name.setGeometry(QtCore.QRect(450, 160, 90, 40))
        self.label_name.setObjectName("label_name")
        self.label_class = StrongBodyLabel(RegisterInterface)
        self.label_class.setGeometry(QtCore.QRect(450, 210, 90, 40))
        self.label_class.setObjectName("label_class")
        self.label_id = StrongBodyLabel(RegisterInterface)
        self.label_id.setGeometry(QtCore.QRect(450, 110, 90, 40))
        self.label_id.setObjectName("label_id")
        self.label_title = StrongBodyLabel(RegisterInterface)
        self.label_title.setGeometry(QtCore.QRect(300, 20, 240, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.label_gender = StrongBodyLabel(RegisterInterface)
        self.label_gender.setGeometry(QtCore.QRect(450, 260, 90, 40))
        self.label_gender.setObjectName("label_gender")
        self.label_birth = StrongBodyLabel(RegisterInterface)
        self.label_birth.setGeometry(QtCore.QRect(450, 310, 90, 40))
        self.label_birth.setObjectName("label_birth")
        self.label_email = StrongBodyLabel(RegisterInterface)
        self.label_email.setGeometry(QtCore.QRect(450, 360, 90, 40))
        self.label_email.setObjectName("label_email")
        self.label_phone = StrongBodyLabel(RegisterInterface)
        self.label_phone.setGeometry(QtCore.QRect(450, 410, 90, 40))
        self.label_phone.setObjectName("label_phone")

        self.input_id = LineEdit(RegisterInterface)
        self.input_id.setGeometry(QtCore.QRect(550, 110, 180, 30))
        self.input_id.setObjectName("input_id")
        self.input_name = LineEdit(RegisterInterface)
        self.input_name.setGeometry(QtCore.QRect(550, 160, 180, 30))
        self.input_name.setObjectName("input_name")
        self.input_class = LineEdit(RegisterInterface)
        self.input_class.setGeometry(QtCore.QRect(550, 210, 180, 30))
        self.input_class.setObjectName("input_class")
        self.input_gender_male = RadioButton(RegisterInterface)
        self.input_gender_male.setGeometry(QtCore.QRect(550, 265, 50, 30))
        self.input_gender_male.setObjectName("input_gender_male")
        self.input_gender_male.setText("男")
        self.input_gender_female = RadioButton(RegisterInterface)
        self.input_gender_female.setGeometry(QtCore.QRect(610, 265, 50, 30))
        self.input_gender_female.setObjectName("input_gender_female")
        self.input_gender_female.setText("女")
        self.input_gender = QButtonGroup(RegisterInterface)
        self.input_gender.setObjectName("input_gender")
        self.input_gender.addButton(self.input_gender_male)
        self.input_gender.addButton(self.input_gender_female)
        self.input_birth = ZhDatePicker(RegisterInterface)
        self.input_birth.setDate(QDate.currentDate())
        self.input_birth.setGeometry(QtCore.QRect(535, 310, 180, 30))
        self.input_birth.setObjectName("input_birth")
        self.input_email = LineEdit(RegisterInterface)
        self.input_email.setGeometry(QtCore.QRect(550, 360, 180, 30))
        self.input_email.setObjectName("input_email")
        self.input_phone = LineEdit(RegisterInterface)
        self.input_phone.setGeometry(QtCore.QRect(550, 410, 180, 30))
        self.input_phone.setObjectName("input_phone")

        self.registerfaceButt = PushButton(RegisterInterface)
        self.registerfaceButt.setGeometry(QtCore.QRect(100, 470, 140, 30))
        self.registerfaceButt.setObjectName("register_face_button")
        self.finishButt = PushButton(RegisterInterface)
        self.finishButt.setGeometry(QtCore.QRect(500, 470, 140, 30))
        self.finishButt.setObjectName("finish_button")

        self.retranslateUi(RegisterInterface)
        QtCore.QMetaObject.connectSlotsByName(RegisterInterface)
        RegisterInterface.setTabOrder(self.input_id, self.input_name)
        RegisterInterface.setTabOrder(self.input_name, self.input_class)
        RegisterInterface.setTabOrder(self.input_class, self.input_gender_male)
        RegisterInterface.setTabOrder(self.input_gender_male, self.input_birth)
        RegisterInterface.setTabOrder(self.input_birth, self.input_email)
        RegisterInterface.setTabOrder(self.input_email, self.input_phone)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("registerFaceInterface", "registerFaceInterface"))
        self.label_title.setText(_translate("registerFaceInterface", "人脸识别个人信息采集"))
        self.label_name.setText(_translate("registerFaceInterface", "请输入姓名*："))
        self.label_class.setText(_translate("registerFaceInterface", "请输入班级*："))
        self.label_id.setText(_translate("registerFaceInterface", "请输入学号*："))
        self.label_gender.setText(_translate("registerFaceInterface", "请输入性别："))
        self.label_birth.setText(_translate("registerFaceInterface", "请输入生日："))
        self.label_email.setText(_translate("registerFaceInterface", "请输入邮件*："))
        self.label_phone.setText(_translate("registerFaceInterface", "请输入手机号："))
        self.registerfaceButt.setText(_translate("registerFaceInterface", "采集人脸数据"))
        self.finishButt.setText(_translate("registerFaceInterface", "上传数据"))