# -*- coding: utf-8 -*-

# Form implementation generated from reading gui file '/Users/taohong/Programs/course-projects/face-detect/gui/pyqt_ui/record_face_dialog.gui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLabel
from qfluentwidgets import PushButton


class Ui_recordFace(object):
    def setupUi(self, QWidget):
        QWidget.setObjectName("Dialog")
        QWidget.resize(800, 600)
        self.saveButt = PushButton(QWidget)
        self.saveButt.setGeometry(50, 520, 80, 30)
        self.saveButt.setObjectName("saveButt")
        self.saveLabel = QLabel(QWidget)
        self.saveLabel.setGeometry(170, 510, 100, 50)
        self.saveLabel.setObjectName("saveLabel")
        self.saveLabel.setText("已采集0份人脸数据")
        self.cancelButt = PushButton(QWidget)
        self.cancelButt.setGeometry(570, 520, 80, 30)
        self.cancelButt.setObjectName("cancelButt")
        self.submitButt = PushButton(QWidget)
        self.submitButt.setGeometry(670, 520, 80, 30)
        self.submitButt.setObjectName("submitButt")
        self.cameraLabel = QtWidgets.QLabel(QWidget)
        self.cameraLabel.setGeometry(QtCore.QRect(40, 20, 720, 450))
        self.cameraLabel.setObjectName("cameraLabel")

        self.retranslateUi(QWidget)
        QtCore.QMetaObject.connectSlotsByName(QWidget)

    def retranslateUi(self, QWidget):
        _translate = QtCore.QCoreApplication.translate
        QWidget.setWindowTitle(_translate("QWidget", "上传人脸"))
        self.saveButt.setText(_translate("QWidget", "添加"))
        self.cancelButt.setText(_translate("QWidget", "取消"))
        self.submitButt.setText(_translate("QWidget", "保存"))
        self.cameraLabel.setText(_translate("QWidget", "TextLabel"))
        self.saveLabel.setText(_translate("QWidget", "已采集0份人脸数据"))
