# -*- coding: utf-8 -*-

# SettingsInterface implementation generated from reading ui file '/Users/taohong/Programs/course-projects/face-detect/gui/pyqt_ui/settings_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from qfluentwidgets import SimpleCardWidget, StrongBodyLabel


class Ui_settingsInterface(object):
    def setupUi(self, SettingsInterface):
        SettingsInterface.setObjectName("SettingsInterface")
        SettingsInterface.resize(850, 620)
        self.frame = SimpleCardWidget(SettingsInterface)
        self.frame.setGeometry(QtCore.QRect(30, 60, 551, 151))
        self.frame.setObjectName("frame")
        self.label_course = QtWidgets.QLabel(self.frame)
        self.label_course.setGeometry(QtCore.QRect(320, 90, 71, 26))
        self.label_course.setObjectName("label_course")
        self.courseComboBox = QtWidgets.QComboBox(self.frame)
        self.courseComboBox.setGeometry(QtCore.QRect(400, 90, 104, 26))
        self.courseComboBox.setObjectName("courseComboBox")
        self.classroomComboBox = QtWidgets.QComboBox(self.frame)
        self.classroomComboBox.setGeometry(QtCore.QRect(400, 30, 104, 26))
        self.classroomComboBox.setObjectName("classroomComboBox")
        self.label_class = QtWidgets.QLabel(self.frame)
        self.label_class.setGeometry(QtCore.QRect(20, 90, 71, 26))
        self.label_class.setObjectName("label_class")
        self.label_building = QtWidgets.QLabel(self.frame)
        self.label_building.setGeometry(QtCore.QRect(20, 30, 71, 26))
        self.label_building.setObjectName("label_building")
        self.label_classroom = QtWidgets.QLabel(self.frame)
        self.label_classroom.setGeometry(QtCore.QRect(320, 30, 71, 26))
        self.label_classroom.setObjectName("label_classroom")
        self.classComboBox = QtWidgets.QComboBox(self.frame)
        self.classComboBox.setGeometry(QtCore.QRect(90, 90, 104, 26))
        self.classComboBox.setObjectName("classComboBox")
        self.buildingComboBox = QtWidgets.QComboBox(self.frame)
        self.buildingComboBox.setGeometry(QtCore.QRect(90, 30, 104, 26))
        self.buildingComboBox.setObjectName("buildingComboBox")
        self.label_5 = StrongBodyLabel(SettingsInterface)
        self.label_5.setGeometry(QtCore.QRect(30, 30, 91, 16))
        self.label_5.setObjectName("label_5")
        self.label_10 = StrongBodyLabel(SettingsInterface)
        self.label_10.setGeometry(QtCore.QRect(30, 250, 91, 16))
        self.label_10.setObjectName("label_10")
        self.frame_2 = SimpleCardWidget(SettingsInterface)
        self.frame_2.setGeometry(QtCore.QRect(30, 280, 551, 111))
        self.frame_2.setObjectName("frame_2")
        self.label_schedule_info = QtWidgets.QLabel(self.frame_2)
        self.label_schedule_info.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.label_schedule_info.setObjectName("label_schedule_info")
        self.label_period = QtWidgets.QLabel(self.frame_2)
        self.label_period.setGeometry(QtCore.QRect(20, 60, 111, 26))
        self.label_period.setObjectName("label_period")
        self.timeEdit = QtWidgets.QTimeEdit(self.frame_2)
        self.timeEdit.setGeometry(QtCore.QRect(130, 60, 118, 24))
        self.timeEdit.setObjectName("timeEdit")
        self.timeEdit.setDisplayFormat("HH:mm:ss")
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.frame_2)
        self.timeEdit_2.setGeometry(QtCore.QRect(310, 60, 118, 24))
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.timeEdit_2.setDisplayFormat("HH:mm:ss")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(270, 60, 21, 26))
        self.label_3.setObjectName("label_3")
        self.schedule_info = QtWidgets.QLabel(self.frame_2)
        self.schedule_info.setGeometry(QtCore.QRect(100, 20, 500, 16))
        self.schedule_info.setObjectName("schedule_info")

        self.retranslateUi(SettingsInterface)
        QtCore.QMetaObject.connectSlotsByName(SettingsInterface)

    def retranslateUi(self, SettingsInterface):
        _translate = QtCore.QCoreApplication.translate
        SettingsInterface.setWindowTitle(_translate("SettingsInterface", "SettingsInterface"))
        self.label_course.setText(_translate("SettingsInterface", "考勤课程："))
        self.label_class.setText(_translate("SettingsInterface", "考勤班级："))
        self.label_building.setText(_translate("SettingsInterface", "考勤地点："))
        self.label_classroom.setText(_translate("SettingsInterface", "考勤教室："))
        self.label_5.setText(_translate("SettingsInterface", "考勤课程设置："))
        self.label_10.setText(_translate("SettingsInterface", "考勤时间设置："))
        self.label_schedule_info.setText(_translate("SettingsInterface", "课程信息："))
        self.label_period.setText(_translate("SettingsInterface", "考勤时间设置："))
        self.label_3.setText(_translate("SettingsInterface", "至"))
        self.schedule_info.setText(_translate("SettingsInterface", "请先选择课程"))
